---

ssh_path: ~/.ssh/id_rsa
ssh_size: 4096
ssh_comment: macbook

git_mail: user@example.com
git_name: MayNiklas
git_editor: "subl -n -w"

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_apps:
  - signal
  - discord
  - telegram
  - teamspeak-client
  - whatsapp
  - docker
  - firefox
  - chromium
  - tor-browser
  - adobe-creative-cloud 
  - jetbrains-toolbox
  - github
  - spotify
  - vlc
  - obs
  - parsec
  - plex
  - ultimaker-cura
  - sublime-text
  - filebot
  - cyberduck
  - forklift
  - balenaetcher
  - cleanmymac
  - synology-drive
  - wacom-tablet
  - yubico-authenticator
  - eizo-colornavigator
  - vmware-fusion

homebrew_packages:
  - mas
  - ansible
  - iperf3
  - nmap
  - wakeonlan
  - fish
  - git
  - wget
  - hugo
  - gradle
  - htop
  - glances
  - docker-compose

mas_apps:
  - { name: 1Password 7 - Password Manager, id: 1333542190 }
  - { name: Twitter, id: 1482454543 }
  - { name: WireGuard, id: 1451685025 }
  - { name: Microsoft Excel, id: 462058435 }
  - { name: Microsoft Remote Desktop, id: 1295203466 }
  - { name: Magnet, id: 441258766 }
  - { name: Parcel - Delivery Tracking, id: 639968404 }



