---

- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - role: ansible-git
      when: configure_git
    - role: ansible-ssh
      when: configure_ssh
    - role: ansible-osx_defaults
      when: configure_osx
    - role: ansible-homebrew
      when: configure_brew
    - role: ansible-mas
      when: configure_mas