---

- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  roles:
    - role: ansible-git    
    - role: ansible-ssh
    - role: ansible-osx_defaults
    - role: ansible-homebrew
    - role: ansible-mas
