---
# roles:
#   - src: 'https://github.com/MayNiklas/ansible-git.git'
#     name: ansible-git
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-yubikey-mac.git'
#     name: ansible-yubikey
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-ssh.git'
#     name: ansible-ssh
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-osx_defaults.git'
#     name: ansible-osx_defaults
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-homebrew.git'
#     name: ansible-homebrew
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-mas.git'
#     name: ansible-mas
#     scm: git
#   - src: 'https://github.com/MayNiklas/ansible-shell-mac.git'
#     name: ansible-shell-mac
#     scm: git

collections:
  - name: community.general
    source: https://galaxy.ansible.com
