---

- hosts: localhost
  roles:
    - role: ansible-git
      when: configure_git
    - role: ansible-yubikey
      when: configure_yubikey
    - role: ansible-ssh
      when: configure_ssh
    - role: ansible-osx_defaults
      when: configure_osx
    - role: ansible-homebrew
      when: configure_brew
    - role: ansible-mas
      when: configure_mas
