---
# set up Mac OS settings via defaults
configure_osx: true

# set up gnupg as ssh-agent
configure_yubikey: true

configure_shell: true

configure_vscode: true
vscode_extensions:
  - DavidAnson.vscode-markdownlint
  - GitHub.codespaces
  - GitHub.copilot
  - GitHub.copilot
  - GitHub.copilot-chat
  - GitHub.github-vscode-theme
  - GitHub.remotehub
  - github.vscode-github-actions
  - GitHub.vscode-pull-request-github
  - golang.go
  - James-Yu.latex-workshop
  - ms-azuretools.vscode-docker
  - ms-python.autopep8
  - ms-python.black-formatter
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode.remote-explorer
  - ms-vscode.remote-repositories
  - ms-vscode.remote-server
  - ms-vsliveshare.vsliveshare
  - redhat.ansible
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - REditorSupport.r
  - rust-lang.rust-analyzer
  - yzhang.markdown-all-in-one

# generate /etc/hosts & ~/.ssh/config
configure_hosts: true
ssh_config:
  - { ip: 192.168.5.20, host: aida, user: nik }
  - { ip: 192.168.5.21, host: kora, user: nik, forward: true }
  - { ip: 192.168.20.5, host: bob }
  - { ip: 192.168.20.10, host: simmons, user: nik }
  - { ip: 10.88.88.17, host: rtx3060, user: nik }
  - { ip: 5.45.108.206, host: lamafarm, port: 50937 }
  - { ip: 5.45.108.206, host: lasse, user: nik, port: 25564 }
  - { ip: matrix.lounge.rocks, host: the-bus, user: nik }
  - { ip: wg.nik-ste.de, host: the-hub, user: nik }
  - { ip: 202.61.248.243, host: mobi }
  - { ip: oracle-aarch64-runner-1.lounge.rocks, host: oracle-aarch64-runner-1 }
  - { ip: netcup-x86-runner-1.lounge.rocks, host: netcup-x86-runner-1 }

# generate ssh key
configure_ssh: false
ssh_path: ~/.ssh/id_rsa
ssh_size: 4096
ssh_comment: macbook

# configure git config
configure_git: true
git_mail: info@niklas-steffen.de
git_name: MayNiklas
git_ignore:
  - "### macOS ###"
  - "# General"
  - .DS_Store
  - .AppleDouble
  - .LSOverride
  - "# nix build file"
  - result
  - "## Core latex/pdflatex auxiliary files:"
  - "*.aux"
  - "*.lof"
  - "*.log"
  - "*.lot"
  - "*.fls"
  - "*.out"
  - "*.toc"
  - "*.fmt"
  - "*.fot"
  - "*.cb"
  - "*.cb2"
  - ".*.lb"

# install stuff via brew
configure_brew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_taps_github:
  - { name: alexanderwallau/bonn-mensa, url: https://github.com/alexanderwallau/bonn-mensa }
  - { name: lounge-rocks/crab_share, url: https://github.com/lounge-rocks/crab_share }

homebrew_apps:
  - adobe-creative-cloud
  # - autodesk-fusion360
  - balenaetcher
  - bambu-studio
  - discord
  - docker
  - element
  - firefox
  - freecad
  - github
  - jetbrains-toolbox
  - mactex-no-gui
  - monitorcontrol
  - obs
  - obs-ndi
  - obsidian
  - orcaslicer
  - plex
  - raspberry-pi-imager
  - signal
  - sonos
  - sony-ps-remote-play
  - spotify
  - steam
  - sublime-merge
  - sublime-text
  - synology-drive
  - telegram
  - via
  - visual-studio-code
  - vlc
  - wireshark
  - yubico-authenticator
  - yubico-yubikey-manager
  - zoom

homebrew_packages:
  - ansible
  - ansible-lint
  - asciinema
  - bonn-mensa
  - crab_share
  - ffmpeg
  - fzf
  - go
  - htop
  - hugo
  - iperf3
  - latexindent
  - nmap
  - openai-whisper
  - pre-commit
  - r
  - rustup
  - wakeonlan
  - wget
  - yt-dlp

# install stuff via app Store
configure_mas: true
mas_apps:
  - { name: 1Password 7 - Password Manager, id: 1295203466 }
  - { name: Apple Configurator 2, id: 1037126344 }
  - { name: Final Cut Pro, id: 424389933 }
  - { name: Magnet, id: 1333542190 }
  - { name: Microsoft Excel, id: 1482454543 }
  - { name: Microsoft Word, id: 462054704 }
  - { name: Microsoft Remote Desktop, id: 639968404 }
  - { name: Parcel - Delivery Tracking, id: 462058435 }
  - { name: Twitter, id: 1451685025 }
  - { name: WhatsApp Messenger, id: 310633997 }
  - { name: WireGuard, id: 441258766 }
