---
# set up Mac OS settings via defaults
configure_osx: true

# set up gnupg as ssh-agent
configure_yubikey: true

configure_shell: true

# generate /etc/hosts & ~/.ssh/config
configure_hosts: true
ssh_config:
  - { ip: 192.168.20.5, host: bob, user: root, port: 22 }
  - { ip: 192.168.5.20, host: aida, user: nik, port: 22 }
  - { ip: 192.168.5.21, host: kora, user: nik, port: 22 }
  - { ip: 5.45.108.206, host: lamafarm, user: root, port: 50937 }
  - { ip: matrix.lounge.rocks, host: the-bus, user: nik, port: 22 }
  - { ip: wg.nik-ste.de, host: the-hub, user: nik, port: 22 }
  - { ip: 202.61.248.243, host: mobi, user: root, port: 22 }
  - { ip: lounge.rocks, host: lounge.rocks, user: root, port: 22 }
  - { ip: oracle-aarch64-runner-1.lounge.rocks, host: oracle-aarch64-runner-1, user: root, port: 22 }
  - { ip: netcup-x86-runner-1.lounge.rocks, host: netcup-x86-runner-1, user: root, port: 22 }

# generate ssh key
configure_ssh: false
ssh_path: ~/.ssh/id_rsa
ssh_size: 4096
ssh_comment: macbook

# configure git config
configure_git: true
git_mail: info@niklas-steffen.de
git_name: MayNiklas
# git_ignore: []

# install stuff via brew
configure_brew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - drone/drone

homebrew_apps:
  - adobe-creative-cloud
  - discord
  - docker
  - element
  - firefox
  - github
  - jetbrains-toolbox
  - monitorcontrol
  - plex
  - signal
  - spotify
  - sublime-text
  - telegram
  - vlc
  - visual-studio-code
  - yubico-authenticator
  - zoom

homebrew_packages:
  - ansible
  - ansible-lint
  - asciinema
  - docker-compose
  - git
  - glances
  - htop
  - hugo
  - iperf3
  - mas
  - nmap
  - wakeonlan
  - wget

# install stuff via app Store
configure_mas: true
mas_apps:
  - { name: 1Password 7 - Password Manager, id: 1295203466 }
  - { name: Apple Configurator 2, id: 1037126344 }
  - { name: Blackmagic Disk Speed Test, id: 425264550 }
  - { name: Final Cut Pro, id: 424389933 }
  - { name: Magnet, id: 1333542190 }
  - { name: Microsoft Excel, id: 1482454543 }
  - { name: Microsoft Remote Desktop, id: 639968404 }
  - { name: Parcel - Delivery Tracking, id: 462058435 }
  - { name: Twitter, id: 1451685025 }
  - { name: WhatsApp Desktop, id: 1147396723 }
  - { name: WireGuard, id: 441258766 }
