---

configure_osx: true

configure_yubikey: true

configure_shell: true

configure_ssh: false
ssh_path: ~/.ssh/id_rsa
ssh_size: 4096
ssh_comment: macbook

configure_git: yes
git_mail: info@niklas-steffen.de
git_name: MayNiklas

configure_brew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - drone/drone

homebrew_apps:
  - adobe-creative-cloud
  - balenaetcher
  - chromium
  - cleanmymac
  - discord
  - docker
  - eizo-colornavigator
  - filebot
  - firefox
  - forklift
  - github
  - jetbrains-toolbox
  - monitorcontrol
  - obs
  - plex
  - signal
  - spotify
  - sublime-text
  - telegram
  - tor-browser
  - ultimaker-cura
  - vlc
  - visual-studio-code
  - vmware-fusion
  - whatsapp
  - yubico-authenticator

homebrew_packages:
  - ansible
  - docker-compose
  - drone
  - fish
  - git
  - glances
  - gradle
  - htop
  - hugo
  - iperf3
  - mas
  - nmap
  - wakeonlan
  - wget

configure_mas: true
mas_apps:
  - { name: 1Password 7 - Password Manager,id: 1295203466 }
  - { name: Apple Configurator 2,id: 1037126344 }
  - { name: Magnet,id: 1333542190 }
  - { name: Twitter,id: 1451685025 }
  - { name: Microsoft Excel,id: 1482454543 }
  - { name: WireGuard,id: 441258766 }
  - { name: Parcel - Delivery Tracking,id: 462058435 }
  - { name: Microsoft Remote Desktop,id: 639968404 }



