---
# tasks file for ansible-ssh

- name: Create ~/.ssh if directory does not exist
  file:
    path: ~/.ssh
    state: directory

- name: generate SSH key
  openssh_keypair:
    state: present
    comment: "{{ ssh_comment }}"
    type: rsa
    size: "{{ ssh_size }}"
    path: "{{ ssh_path }}"
  register: task_result

- name: add new key to ssh-agent 
  shell: ssh-add -K {{ ssh_path }}
  when: task_result is changed
